### ISSUE TITLE
Exception thrown when trying to load a world file

### ISSUE THREAD

**Issue by Leative** [Neop/mudmap2#4]
Hi there,
choosing "open" from the file menu throws an exception.

```
Mai 19, 2017 11:49:55 AM mudmap2.frontend.dialog.OpenWorldDialog$1 accept
SEVERE: null
java.nio.channels.ClosedByInterruptException
	at java.nio.channels.spi.AbstractInterruptibleChannel.end(Unknown Source)
	at sun.nio.ch.FileChannelImpl.size(Unknown Source)
	at java.nio.file.Files.readAllBytes(Unknown Source)
	at mudmap2.backend.WorldFileReader.current.WorldFileJSON.getJSONRoot(WorldFileJSON.java:88)
	at mudmap2.backend.WorldFileReader.current.WorldFileJSON.readWorldName(WorldFileJSON.java:687)
	at mudmap2.backend.WorldFileReader.current.WorldFileDefault.readWorldName(WorldFileDefault.java:115)
	at mudmap2.frontend.dialog.OpenWorldDialog$1.accept(OpenWorldDialog.java:66)
	at javax.swing.JFileChooser.accept(Unknown Source)
	at javax.swing.plaf.basic.BasicDirectoryModel$LoadFilesThread.run0(Unknown Source)
	at javax.swing.plaf.basic.BasicDirectoryModel$LoadFilesThread.run(Unknown Source)
```

The problem lies in the constructor of WorldFileDefault in the switch statement. Even if an INVALID or UNKNOWN file is detected, the switch case for JSON-files is executed.
Put INVALID, UNKNOWN and default cases to the bottom of the switch to fix this.

Best regards,
Stefan

**Comment by Neop** [comment]
Thank your for your feedback!
This might not be best code but it was intended to chose the JSON class in default case, then check if the file is readable by calling another method canRead(). I chose this approach so a WorldFileDefault can always be used to save an opened world file (instead of possibly breaking and causing data loss then).

Seems the readability check method was missing at some places. Adding it made the exception disappear in my quick tests. I hope this fixes your problem: https://github.com/Neop/mudmap2/releases/tag/v2.4.2

**Comment by Leative** [comment]
Ok, I didn't realize this order might have an effect on persistence as well. Didn't dig deep enough into the code.

The Exception seems to be thread related, though. Sometimes it occurs, sometimes not. However, it only seems to occur at maximum one time after the tool was started.

**Comment by Neop** [comment]
I don't expect anyone to read all this code, it got too complex even for me to know all hidden things and analyze their effects in my little time, which is why decided against your suggestion. I appreciate it though.
Anyway, I found and added two more missing checks, each of them should fix this issue on it's own.
https://github.com/Neop/mudmap2/releases/tag/v2.4.3
